nmap -sP 192.168.1.0/24




rtsp://admin:admin@192.168.1.10:554/live/main

rtsp://192.168.1.12:554/user=admin_password=_channel=1_stream=0.sdp

rtsp://192.168.1.13:554/user=admin_password=_channel=1_stream=0.sdp

rtsp://admin:admin@192.168.1.14:554/live

rtsp://192.168.1.15:554/user=admin_password=_channel=1_stream=0.sdp

rtsp://192.168.1.16:8554/user=admin_password=_channel=1_stream=0.sdp


на windows это открылось в VLC:
    rtsp://admin:admin@192.168.1.10:554/live/main

    

vlc rtsp://admin:admin@192.168.1.10:554/live/sub
vlc rtsp://192.168.1.10:554/user=admin_password=_channel=1_stream=0.sdp
vlc rtsp://admin:admin@192.168.1.10:554/live


vlc rtsp://admin:admin@192.168.1.12:554/live/sub
vlc rtsp://192.168.1.12:554/user=admin_password=_channel=1_stream=0.sdp
vlc rtsp://admin:admin@192.168.1.12:554/live


vlc rtsp://admin:admin@192.168.1.13:554/live/sub
vlc rtsp://192.168.1.13:554/user=admin_password=_channel=1_stream=0.sdp
vlc rtsp://admin:admin@192.168.1.13:554/live

vlc rtsp://admin:admin@192.168.1.14:554/live/sub
cvlc rtsp://192.168.1.14:554/user=admin_password=_channel=1_stream=0.sdp
cvlc rtsp://admin:admin@192.168.1.14:554/live

vlc rtsp://admin:admin@192.168.1.15:554/live/sub
vlc rtsp://192.168.1.15:554/user=admin_password=_channel=1_stream=0.sdp
vlc rtsp://admin:admin@192.168.1.15:554/live

vlc rtsp://admin:admin@192.168.1.16:554/live/sub
vlc rtsp://192.168.1.16:554/user=admin_password=_channel=1_stream=0.sdp
vlc rtsp://admin:admin@192.168.1.16:554/live





SRC_VIDEO_STREAM = rtsp://admin:admin@172.16.78.253:10554/live/sub
SRC_VIDEO_STREAM = rtsp://admin:admin@172.16.78.253:10554/live/sub
SRC_VIDEO_STREAM = rtsp://172.16.78.253:11554/user=admin_password=_channel=1_stream=0.sdp
SRC_VIDEO_STREAM = rtsp://172.16.78.253:12554/user=admin_password=_channel=1_stream=0.sdp
SRC_VIDEO_STREAM = rtsp://172.16.78.253:13554/user=admin_password=_channel=1_stream=0.sdp
SRC_VIDEO_STREAM = rtsp://admin:admin@172.16.78.253:14554/live
SRC_VIDEO_STREAM = rtsp://172.16.78.253:12554/user=admin_password=_channel=1_stream=0.sdp


